services:
  starbound-server:
    image: islands04/starbound-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "21025:21025/tcp"
    volumes:
      - /servers/starbound:/steamcmd/starbound:cached


